version: '3'

services:
  consultorio:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: "./.docker/run.sh"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./.docker/initdb:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: consultorio_qualidade
      MYSQL_ROOT_PASSWORD: root